name: ECDSA features

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --no-default-features --features ecdsa,sha2 --verbose
    - name: Run tests
      run: cargo test --no-default-features --features ecdsa,sha2 --verbose
