name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build default
      run: cargo build --verbose
    - name: Run default tests
      run: cargo test --verbose
    - name: Build dsa
      run: cargo build --no-default-features --features dsa,sha1 --verbose
    - name: Run dsa tests
      run: cargo test --no-default-features --features dsa,sha1 --verbose
    - name: Build rsa
      run: cargo build --no-default-features --features rsa,sha1,sha2 --verbose
    - name: Run rsa tests
      run: cargo test --no-default-features --features rsa,sha1,sha2 --verbose
    - name: Build ecdsa
      run: cargo build --no-default-features --features ecdsa,sha2 --verbose
    - name: Run ecdsa tests
      run: cargo test --no-default-features --features ecdsa,sha2 --verbose
    - name: Build ed25519
      run: cargo build --no-default-features --features ed25519,sha2 --verbose
    - name: Run ed25519 tests
      run: cargo test --no-default-features --features ed25519,sha2 --verbose
    - name: Build all
      run: cargo build --all-features --verbose
    - name: Run all tests
      run: cargo test --all-features --verbose
