name: x509-verify

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    strategy:
      matrix:
        rust:
          - 1.65.0
          - stable
        target:
          - thumbv7em-none-eabi
          - wasm32-unknown-unknown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
      - uses: taiki-e/install-action@cargo-hack
      - run: cargo hack build --target ${{ matrix.target }} --feature-powerset --skip x509-cert

  test:
    strategy:
      matrix:
        rust:
          - 1.65.0
          - stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: taiki-e/install-action@cargo-hack
      - run: cargo hack test --feature-powerset --feature-powerset --skip x509-cert
