name: x509-verify

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    strategy:
      matrix:
        rust:
          - 1.65.0
          - stable
        target:
          - thumbv7em-none-eabi
          - wasm32-unknown-unknown
        features:
          - dsa,sha1
          - rsa,sha1,sha2
          - k256,sha2
          - p192,sha2
          - p224,sha2
          - p256,sha2
          - p384,sha2
          - ecdsa,sha2
          - ed25519,sha2
          - md2,md5,sha1,sha2,dsa,rsa,ecdsa,ed25519
          - md2,md5,sha1,sha2,dsa,rsa,ecdsa,ed25519,x509,pem
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
      - run: cargo build --target ${{ matrix.target }} --no-default-features --features ${{ matrix.features }}

  test:
    strategy:
      matrix:
        rust:
          - 1.65.0
          - stable
        features:
          - dsa,sha1
          - rsa,sha1,sha2
          - k256,sha2
          - p192,sha2
          - p224,sha2
          - p256,sha2
          - p384,sha2
          - ecdsa,sha2
          - ed25519,sha2
          - md2,md5,sha1,sha2,dsa,rsa,ecdsa,ed25519
          - md2,md5,sha1,sha2,dsa,rsa,ecdsa,ed25519,x509,pem
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo test --no-default-features --features ${{ matrix.features }}
