name: x509-verify

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    strategy:
      matrix:
        rust:
          - 1.81.0
          - stable
        target:
          - thumbv7em-none-eabi
          - wasm32-unknown-unknown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
      - run: cargo build --target ${{ matrix.target }} --no-default-features --features dsa,sha1
      - run: cargo build --target ${{ matrix.target }} --no-default-features --features rsa,sha1,sha2
      - run: cargo build --target ${{ matrix.target }} --no-default-features --features k256,sha2
      - run: cargo build --target ${{ matrix.target }} --no-default-features --features p192,sha2
      - run: cargo build --target ${{ matrix.target }} --no-default-features --features p224,sha2
      - run: cargo build --target ${{ matrix.target }} --no-default-features --features p256,sha2
      - run: cargo build --target ${{ matrix.target }} --no-default-features --features p384,sha2
      - run: cargo build --target ${{ matrix.target }} --no-default-features --features ecdsa,sha2
      - run: cargo build --target ${{ matrix.target }} --no-default-features --features ed25519,sha2
      - run: cargo build --target ${{ matrix.target }} --no-default-features --features md2,md5,sha1,sha2,dsa,rsa,ecdsa,ed25519
      - run: cargo build --target ${{ matrix.target }} --no-default-features --features md2,md5,sha1,sha2,dsa,rsa,ecdsa,ed25519,x509,pem

  test:
    strategy:
      matrix:
        rust:
          - 1.81.0
          - stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo test --no-default-features --features dsa,sha1
      - run: cargo test --no-default-features --features rsa,sha1,sha2
      - run: cargo test --no-default-features --features k256,sha2
      - run: cargo test --no-default-features --features p192,sha2
      - run: cargo test --no-default-features --features p224,sha2
      - run: cargo test --no-default-features --features p256,sha2
      - run: cargo test --no-default-features --features p384,sha2
      - run: cargo test --no-default-features --features ecdsa,sha2
      - run: cargo test --no-default-features --features ed25519,sha2
      - run: cargo test --no-default-features --features md2,md5,sha1,sha2,dsa,rsa,ecdsa,ed25519
      - run: cargo test --no-default-features --features md2,md5,sha1,sha2,dsa,rsa,ecdsa,ed25519,x509,pem
